user:
  outputs:
    default:
      account: BNWTXOW-QW31587
      auth_type: keypair
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: DV_PROTOTYPE_DB
      private_key_path: /tmp/.dbt/keyfile.pem
      retry_on_database_errors: true
      role: null
      schema: DEMO
      threads: 6
      type: snowflake
      user: SHREYASHTHENGNE
      warehouse: DV_PROTOTYPE_WH
  target: default
