version: 2
models:
- name: sat_inv_inventory_details
  columns:
  - name: INVENTORY_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - INVENTORY_PK
      - LOAD_DATE
- name: sat_inv_part_details
  columns:
  - name: PART_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - PART_PK
      - LOAD_DATE
- name: sat_inv_supp_nation_details
  columns:
  - name: SUPPLIER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - SUPPLIER_PK
      - LOAD_DATE
- name: sat_inv_supp_region_details
  columns:
  - name: SUPPLIER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - SUPPLIER_PK
      - LOAD_DATE
- name: sat_inv_supplier_details
  columns:
  - name: SUPPLIER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - SUPPLIER_PK
      - LOAD_DATE
- name: sat_order_cust_nation_details
  columns:
  - name: CUSTOMER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - CUSTOMER_PK
      - LOAD_DATE
- name: sat_order_cust_region_details
  columns:
  - name: CUSTOMER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - CUSTOMER_PK
      - LOAD_DATE
- name: sat_order_customer_details
  columns:
  - name: CUSTOMER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - CUSTOMER_PK
      - LOAD_DATE
- name: sat_order_lineitem_details
  columns:
  - name: LINEITEM_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - LINEITEM_PK
      - LOAD_DATE
- name: sat_order_order_details
  columns:
  - name: ORDER_PK
    tests:
    - not_null
  tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - ORDER_PK
      - LOAD_DATE
